;/*FB_PKG_DELIM*/

__d("useCIXLogMutation_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4924544677638390"}),null);
__d("useCIXLogMutation.graphql",["useCIXLogMutation_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"input"}],c=[{alias:null,args:[{kind:"Variable",name:"input",variableName:"input"}],concreteType:"CIXLoggerOutput",kind:"LinkedField",name:"cix_log",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],storageKey:null}];return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"useCIXLogMutation",selections:c,type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"useCIXLogMutation",selections:c},params:{id:b("useCIXLogMutation_facebookRelayOperation"),metadata:{},name:"useCIXLogMutation",operationKind:"mutation",text:null}}}();e.exports=a}),null);
__d("ProfileCometBlockProfileSOAPInformationDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7167362639972069"}),null);
__d("ProfileCometBlockProfileSOAPInformationDialogQuery$Parameters",["ProfileCometBlockProfileSOAPInformationDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometBlockProfileSOAPInformationDialogQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometBlockProfileSOAPInformationDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CIXShowErrorContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(function(){});g["default"]=b}),98);
__d("useCIXLogMutation",["CometRelay","react","useCIXLogMutation.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h,i=d("react").useCallback,j=h!==void 0?h:h=b("useCIXLogMutation.graphql");function a(){var a=d("CometRelay").useRelayEnvironment();return i(function(b){return d("CometRelay").commitMutation(a,{mutation:j,variables:{input:b}})},[a])}g["default"]=a}),98);
__d("CloseCIXContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext(function(){});g["default"]=b}),98);
__d("CometCompatModalDialogResource",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a=c("JSResourceForInteraction")("CometCompatModal.react").__setRef("CometCompatModalDialogResource");b=a;g["default"]=b}),98);
__d("ProfileCometBlockProfileSOAPInformationDialog.entrypoint",["JSResourceForInteraction","ProfileCometBlockProfileSOAPInformationDialogQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.blockeeID;return{queries:{queryReference:{parameters:b("ProfileCometBlockProfileSOAPInformationDialogQuery$Parameters"),variables:{blockeeID:a}}}}},root:c("JSResourceForInteraction")("ProfileCometBlockProfileSOAPInformationDialog.react").__setRef("ProfileCometBlockProfileSOAPInformationDialog.entrypoint")};g["default"]=a}),98);
__d("CometFRXScreenFooter.react",["fbt","CIXDialogScreenFooter.react","TetraText.react","cr:1030172","gkx","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i=d("react");function a(a){var d=a.buttons,e=a.context;a=a.isIXT;var f=c("gkx")("678680");f=c("gkx")("1820969")&&f&&a;return i.jsx(c("CIXDialogScreenFooter.react"),{buttons:d,debug:i.jsxs("div",{className:"x78zum5 x1q0g3np x5yr21d",children:[b("cr:1030172")!=null&&e!=null?i.jsx(b("cr:1030172"),{context:e}):null,f===!0&&i.jsx("div",{className:"x6s0dn4 x78zum5 x5yr21d x1y1aw1k",children:i.jsx(c("TetraText.react"),{type:"body4",children:h._("__JHASH__wCD4aoiJGZ-__JHASH__")})})]})})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);